import type { Author, Article, Event } from "@/lib/types";

export const authors: Author[] = [
  {
    id: "author-1",
    name: "Julien Renault",
    avatarUrl: "https://picsum.photos/seed/author1/100/100",
    imageHint: "man portrait",
    bio: "Julien is a leading fashion critic, with a sharp eye for runway trends and the interplay between streetwear and high couture.",
  },
  {
    id: "author-2",
    name: "Lexi Chen",
    avatarUrl: "https://picsum.photos/seed/author2/100/100",
    imageHint: "woman portrait",
    bio: "Lexi is a photographer known for her candid backstage shots at Fashion Week and her portraits of industry icons.",
  },
  {
    id: "author-3",
    name: "Simone Jackson",
    avatarUrl: "https://picsum.photos/seed/author3/100/100",
    imageHint: "woman smiling",
    bio: "Simone covers the business of fashion, from brand strategies at LVMH to the rise of independent designers.",
  },
];

export const articles: Article[] = [
  {
    id: "article-1",
    slug: "asap-rocky-and-kanye-west-the-new-fashion-royalty",
    title: "A$AP Rocky & Kanye West: The New Fashion Royalty",
    subtitle: "How two musicians tore down the walls of high fashion and rewrote the rules of style for a generation.",
    authorId: "author-1",
    coverImage: "https://picsum.photos/seed/asap-kanye/1200/800",
    imageHint: "men fashion",
    content: "For decades, the arbiters of style were confined to Parisian ateliers and legacy fashion houses. Then came Kanye West and A$AP Rocky. These artists didn't just wear luxury brands; they infiltrated them, reimagined them, and ultimately became creative forces in their own right. From Kanye's disruptive Yeezy empire to Rocky's effortless fusion of Dior and streetwear, they have become the new kings of a more democratic, digitally-native fashion landscape. This article traces their ascent, analyzing their impact on brands like Louis Vuitton and Balenciaga, and their role in defining what 'cool' means today. They broke the old rules, proving that influence is no longer dictated from the top down but cultivated from the streets up. Their legacy is not just in the clothes they've worn or designed, but in the doors they've opened for a new generation of multi-hyphenate creatives.",
    tags: ["Kanye West", "ASAP Rocky", "Streetwear", "Culture"],
    category: "Culture",
    publishDate: "2024-05-15T10:00:00Z",
    featured: true,
    editorsPick: false,
  },
  {
    id: "article-2",
    slug: "dior-the-enduring-power-of-the-new-look",
    title: "Dior: The Enduring Power of the New Look",
    subtitle: "From 1947 to today, how Christian Dior's revolutionary silhouette continues to shape modern fashion.",
    authorId: "author-3",
    coverImage: "https://picsum.photos/seed/dior-power/1200/800",
    imageHint: "elegant dress",
    content: "In the post-war austerity of 1947, Christian Dior unveiled a collection that would change fashion forever. Dubbed the 'New Look,' its cinched waists and full, voluminous skirts were a radical statement of optimism and femininity. Today, the spirit of the New Look lives on. Creative directors from John Galliano to Maria Grazia Chiuri have reinterpreted its core tenets for a contemporary audience. We explore the evolution of Dior's iconic silhouette, its influence on designers like Yves Saint Laurent, and its lasting cultural impact. The New Look was more than a collection; it was a philosophy that restored a sense of fantasy and elegance to fashion. This visual essay examines key moments, from the original Bar jacket to modern reinterpretations, celebrating a legacy that proves true vision is timeless.",
    tags: ["Dior", "Haute Couture", "Fashion History"],
    category: "Fashion",
    publishDate: "2024-05-14T12:00:00Z",
    featured: true,
    editorsPick: true,
  },
  {
    id: "article-3",
    slug: "the-age-of-the-supermodel-beyond-the-runway",
    title: "The Age of the Supermodel: Beyond the Runway",
    subtitle: "How today's high fashion models are leveraging their platforms to become powerful cultural figures.",
    authorId: "author-2",
    coverImage: "https://picsum.photos/seed/supermodels-runway/1200/800",
    imageHint: "models posing",
    content: "There was a time when models were simply beautiful canvases for a designer's vision. Today, they are brands in their own right. Figures like Bella Hadid, Kendall Jenner, and Adut Akech are not just faces; they are powerful entrepreneurs, activists, and media moguls with global influence that extends far beyond the catwalk. This piece explores the new paradigm of the supermodel in the digital age. We examine how social media has given them a direct line to their audience, allowing them to shape conversations around body positivity, sustainability, and social justice. Through exclusive interviews and analysis, we uncover how these models are navigating the pressures of the industry while building multi-faceted careers that redefine what it means to be a model today. They are the new power players, using their visibility to not just sell clothes, but to inspire change.",
    tags: ["Models", "Culture", "Social Media"],
    category: "Fashion",
    publishDate: "2024-05-12T09:00:00Z",
    featured: false,
    editorsPick: true,
  },
  {
    id: "article-4",
    slug: "balenciaga-from-couture-to-street-culture",
    title: "Balenciaga: From Couture to Street Culture",
    subtitle: "Demna Gvasalia's radical transformation of a storied fashion house into a streetwear phenomenon.",
    authorId: "author-1",
    coverImage: "https://picsum.photos/seed/balenciaga-demna/1200/800",
    imageHint: "edgy fashion",
    content: "When Demna Gvasalia took the helm of Balenciaga, he didn't just update its archives; he blew them up. The designer, known for his work with the disruptive collective Vetements, has masterfully merged the architectural legacy of Cristóbal Balenciaga with the raw energy of contemporary street culture. The result is a brand that is both reverent and irreverent, producing oversized hoodies and couture gowns with equal conviction. This article analyzes Demna's genius, from the viral Triple S sneaker that redefined luxury footwear to his meme-worthy runway shows that challenge the very notion of a fashion presentation. He has made Balenciaga the ultimate purveyor of the zeitgeist, capturing the irony and absurdity of modern life in his designs. It's a controversial, often polarizing vision, but one that has made Balenciaga one of the most talked-about brands in the world.",
    tags: ["Balenciaga", "Streetwear", "Demna Gvasalia"],
    category: "Designers",
    publishDate: "2024-05-11T15:00:00Z",
    featured: false,
    editorsPick: false,
  },
  {
    id: "article-5",
    slug: "an-interview-with-a-visionary-designer",
    title: "An Interview With Hedi Slimane",
    subtitle: "Inside the mind of the controversial designer behind Celine, Saint Laurent, and Dior Homme.",
    authorId: "author-1",
    coverImage: "https://picsum.photos/seed/hedi-interview/1200/800",
    imageHint: "man thinking",
    content: "Hedi Slimane is more than a designer; he's a cultural architect. His razor-sharp tailoring and rock-and-roll aesthetic defined the early 2000s at Dior Homme, and his subsequent reinventions of Saint Laurent and Celine have been met with both critical acclaim and furious debate. In a rare and candid conversation, Slimane discusses his singular vision, his obsession with music subcultures, and his uncompromising approach to creativity. He speaks on the importance of photography in his process, his relationship with the artists who inspire him, and why he has consistently ignored the critics. This interview provides a glimpse into the mind of one of fashion's most private and influential figures, a man who has repeatedly proven that the most powerful statement is a clear, unwavering point of view.",
    tags: ["Hedi Slimane", "Saint Laurent", "Celine", "Interview"],
    category: "Designers",
    publishDate: "2024-05-10T11:00:00Z",
    featured: true,
    editorsPick: true,
  },
];

export const events: Event[] = [
  {
    id: "event-1",
    slug: "louis-vuitton-x-pop-up",
    title: "Louis Vuitton 'X' Pop-Up Experience",
    description: "Explore a limited-time installation celebrating 160 years of artistic collaborations at Louis Vuitton. Discover exclusive items and immerse yourself in the world of LV.",
    image: "https://picsum.photos/seed/lv-experience/1200/800",
    imageHint: "luxury fashion",
    location: {
      name: "The Annex",
      address: "451 Art District Rd, Downtown",
    },
    date: "2024-06-05",
    time: "11:00 - 20:00 (EST)",
  },
  {
    id: "event-2",
    slug: "saint-laurent-rive-droite-ephemeral-gallery",
    title: "Saint Laurent Rive Droite Ephemeral Gallery",
    description: "A curated exhibition of art, photography, and design by Anthony Vaccarello. This special event showcases the cultural universe of Saint Laurent in a unique gallery setting.",
    image: "https://picsum.photos/seed/sl-gallery/1200/800",
    imageHint: "minimalist gallery",
    location: {
      name: "Rive Droite Gallery",
      address: "8 Rue de la Paix, Paris",
    },
    date: "2024-06-18",
    time: "10:00 - 19:00 (CET)",
  },
  {
    id: "event-3",
    slug: "balenciaga-couture-screening",
    title: "Screening: Balenciaga's 52nd Couture Show",
    description: "An exclusive cinematic screening of Demna's latest Couture collection for Balenciaga, followed by a panel discussion with leading fashion critics.",
    image: "https://picsum.photos/seed/balenciaga-show/1200/800",
    imageHint: "fashion show",
    location: {
      name: "The Metrograph",
      address: "7 Ludlow St, New York",
    },
    date: "2024-06-25",
    time: "19:30 - 21:30 (EST)",
  },
];
