import type { Author, Article, Event } from "@/lib/types";

export const authors: Author[] = [
  {
    id: "author-1",
    name: "Elena Petrov",
    avatarUrl: "https://picsum.photos/seed/author1/100/100",
    imageHint: "woman portrait",
    bio: "Elena is a renowned fashion photographer and cultural critic with over a decade of experience capturing the zeitgeist.",
  },
  {
    id: "author-2",
    name: "Kenji Tanaka",
    avatarUrl: "https://picsum.photos/seed/author2/100/100",
    imageHint: "man portrait",
    bio: "Kenji specializes in street style and emerging art scenes, bringing a unique perspective from the heart of Tokyo.",
  },
  {
    id: "author-3",
    name: "Aisha Williams",
    avatarUrl: "https://picsum.photos/seed/author3/100/100",
    imageHint: "woman smiling",
    bio: "Aisha is an investigative journalist in the world of sustainable fashion, uncovering stories that matter.",
  },
];

export const articles: Article[] = [
  {
    id: "article-1",
    slug: "the-renaissance-of-haute-couture",
    title: "The Renaissance of Haute Couture",
    subtitle: "How modern designers are redefining bespoke fashion for a new generation.",
    authorId: "author-1",
    coverImage: "https://picsum.photos/seed/article1/1200/800",
    imageHint: "fashion design",
    content: "Haute couture, once the exclusive domain of the world's wealthiest, is experiencing a remarkable resurgence. In an age of fast fashion and mass production, a new wave of designers is championing the art of the handmade, the meticulously crafted, and the deeply personal. This is not merely a return to old-world techniques but a forward-thinking reinterpretation of what luxury means today. Designers are blending traditional skills with cutting-edge technology, such as 3D printing and innovative textile development, to create garments that are both timeless and contemporary. The focus has shifted from ostentatious displays of wealth to a more subtle appreciation for craftsmanship, sustainability, and storytelling. Each piece tells a story, not just of its creation but of the values it represents. This movement is capturing the imagination of a younger, more conscious consumer who seeks authenticity and a connection to the products they buy. The new couture is less about status and more about self-expression, a wearable art form that celebrates individuality in a world of conformity. It's a quiet revolution, stitched one-of-a-kind garment at a time, proving that the most profound luxury is not just owning something beautiful, but something uniquely yours.",
    tags: ["Fashion", "Couture", "Design"],
    category: "Fashion",
    publishDate: "2024-05-15T10:00:00Z",
    featured: true,
    editorsPick: false,
  },
  {
    id: "article-2",
    slug: "tokyo-street-style-a-visual-diary",
    title: "Tokyo Street Style: A Visual Diary",
    subtitle: "Exploring the eclectic and boundary-pushing fashion of Harajuku and Shibuya.",
    authorId: "author-2",
    coverImage: "https://picsum.photos/seed/article2/1200/800",
    imageHint: "tokyo street",
    content: "Tokyo's streets are a living runway, a vibrant tapestry of self-expression where fashion rules are made to be broken. From the whimsical eclecticism of Harajuku to the sleek, avant-garde looks of Shibuya, the city is a constant source of inspiration. This visual diary is a journey through its most iconic fashion districts, capturing the spirit of a culture that celebrates individuality above all else. We witness the bold color palettes of Decora, the dark romanticism of Gothic Lolita, and the minimalist chic of modern Japanese designers. It's a world where vintage finds are mixed with high-fashion pieces, and personal creativity is the ultimate currency. What's most striking is the fearlessness of the youth, who use clothing as a powerful tool for identity formation. The trends are fleeting, but the underlying ethos of experimentation and artistic freedom is a constant. This is more than just clothing; it's a dialogue between tradition and modernity, a performance played out on the city's concrete catwalks. Each photograph in this essay is a snapshot of a moment, a personality, an idea, contributing to the ever-evolving narrative of global fashion.",
    tags: ["Street Style", "Tokyo", "Photography"],
    category: "Photo Essays",
    publishDate: "2024-05-14T12:00:00Z",
    featured: true,
    editorsPick: true,
  },
  {
    id: "article-3",
    slug: "the-art-of-the-unseen-sound-installations",
    title: "The Art of the Unseen: Sound Installations",
    subtitle: "How contemporary artists are using sound to sculpt space and emotion.",
    authorId: "author-1",
    coverImage: "https://picsum.photos/seed/article3/1200/800",
    imageHint: "art gallery",
    content: "In a world dominated by visual stimuli, a growing number of artists are turning to a different medium to create immersive experiences: sound. Sound art and installations challenge our perception of space, time, and emotion, creating environments that are felt as much as they are heard. These artists, or 'sonic architects,' use everything from ambient field recordings to complex digital compositions to transform galleries, public squares, and natural landscapes. The experience is deeply personal; a single soundscape can evoke a spectrum of memories and feelings unique to each listener. It forces a more introspective form of engagement, demanding patience and a willingness to listen deeply. We explore the work of pioneers and contemporary innovators who are pushing the boundaries of the medium, creating invisible sculptures that reshape our reality. Their work questions the primacy of sight and reminds us of the power of the auditory sense to connect us to our environment and to each other in profound ways. This is art that you close your eyes to see.",
    tags: ["Art", "Sound Art", "Installation"],
    category: "Art",
    publishDate: "2024-05-12T09:00:00Z",
    featured: false,
    editorsPick: true,
  },
  {
    id: "article-4",
    slug: "sustainable-fashion-beyond-the-buzzword",
    title: "Sustainable Fashion: Beyond the Buzzword",
    subtitle: "A deep dive into the brands and practices that are truly making a difference.",
    authorId: "author-3",
    coverImage: "https://picsum.photos/seed/article4/1200/800",
    imageHint: "sustainable fabric",
    content: "'Sustainability' has become the fashion industry's favorite buzzword, but what does it really mean? This article moves beyond the greenwashing to spotlight the designers, innovators, and artisans who are embedding ethical and environmental principles into the very fabric of their work. We investigate the entire supply chain, from the sourcing of revolutionary materials like mushroom leather and orange fiber to the implementation of circular economy models that design out waste. We speak with leaders who are prioritizing fair labor practices, championing transparency, and educating consumers about the true cost of their clothing. This is a story of positive change, showcasing that fashion can be a force for good. It's about a return to quality over quantity, a celebration of durable, timeless design that transcends fleeting trends. The future of fashion is not just about looking good, but feeling good about what we wear and the impact it has on our planet and its people. This is a guide to making informed choices and supporting a system that values both style and substance.",
    tags: ["Sustainability", "Ethics", "Fashion"],
    category: "Trends",
    publishDate: "2024-05-11T15:00:00Z",
    featured: false,
    editorsPick: false,
  },
  {
    id: "article-5",
    slug: "an-interview-with-a-visionary-artist",
    title: "An Interview with a Visionary Artist",
    subtitle: "Inside the mind of a creator who is reshaping our cultural landscape.",
    authorId: "author-2",
    coverImage: "https://picsum.photos/seed/article5/1200/800",
    imageHint: "artist studio",
    content: "We sat down with the enigmatic artist known only as 'Observer' for a rare, in-depth conversation about their work, their philosophy, and their vision for the future of art. Known for large-scale, interactive installations that blend technology and natural elements, Observer's work challenges viewers to reconsider their relationship with the world around them. In this interview, we delve into the inspirations behind their most iconic pieces, from the digital waterfall that responds to real-time weather data to the forest of light that breathes with the collective rhythm of its visitors' heartbeats. Observer speaks candidly about the role of the artist in an age of digital distraction, the importance of creating spaces for collective wonder, and the delicate balance between creation and preservation. The conversation reveals a mind that is both deeply analytical and profoundly spiritual, constantly seeking to bridge the gap between the tangible and the intangible. This is not just an interview; it's an invitation to see the world through a different lens, to find the poetry in the code and the humanity in the machine.",
    tags: ["Interview", "Art", "Technology"],
    category: "Culture",
    publishDate: "2024-05-10T11:00:00Z",
    featured: true,
    editorsPick: true,
  },
];

export const events: Event[] = [
  {
    id: "event-1",
    slug: "vernissage-future-landscapes",
    title: "Vernissage: Future Landscapes",
    description: "Join us for the opening night of 'Future Landscapes', a group exhibition featuring digital and mixed-media artists exploring speculative ecologies. Music by DJ Chromatic and refreshments will be served.",
    image: "https://picsum.photos/seed/event1/1200/800",
    imageHint: "abstract art",
    location: {
      name: "The Void Gallery",
      address: "123 Market St, Downtown",
    },
    date: "2024-06-01",
    time: "19:00 - 22:00 (GMT)",
  },
  {
    id: "event-2",
    slug: "runway-show-atelier-x",
    title: "Runway Show: Atelier X",
    description: "A first look at the Fall/Winter collection from the avant-garde design house, Atelier X. This exclusive event will showcase their latest work in an immersive, theatrical presentation.",
    image: "https://picsum.photos/seed/event2/1200/800",
    imageHint: "fashion runway",
    location: {
      name: "Warehouse 7",
      address: "7 Industrial Rd, West End",
    },
    date: "2024-06-15",
    time: "20:00 - 21:00 (EST)",
  },
  {
    id: "event-3",
    slug: "artist-talk-kenji-tanaka",
    title: "Artist Talk: Kenji Tanaka",
    description: "Our very own Kenji Tanaka discusses his process and the stories behind his 'Tokyo Street Style' photo essay. The talk will be followed by a Q&A session and book signing.",
    image: "https://picsum.photos/seed/event3/1200/800",
    imageHint: "lecture hall",
    location: {
      name: "City Art Museum",
      address: "456 Culture Ave, Museum Park",
    },
    date: "2024-06-22",
    time: "14:00 - 15:30 (PST)",
  },
];
